name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.5
      - name: Install dependencies
        run:
          python3 -m pip install z3-solver && julia --project=. -e 'using Pkg; Pkg.test(); Pkg.instantiate(); Pkg.add(["Documenter","DocumenterTools"]);'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: mkdir ~/.ssh && touch ~/.ssh/known_hosts && echo "$DEPLOY_KEY" >> ~/.ssh/known_hosts && cd docs && julia make.jl
